crud_blog/urls.py
from django.urls import path
from .views import home, article, about, register_page, login_page,\
    logout_page, update_article, delete_article, create_article, confirm_delete_article
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from django.contrib.auth.forms import PasswordResetForm
from django.urls import reverse_lazy
from .forms import UserPasswordResetForm, UserPasswordResetConfirmForm


app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('register/', register_page, name="register"),
    path('login/', login_page, name="login"),
    path('logout/', logout_page, name="logout"),

    # Article CRUD
    path('create-article/', create_article, name="create"),
    path('<int:pk>/', article, name="article"),
    path('update/<int:pk>/', update_article, name="update"),
    # path('confirm-delete/<int:pk>/', confirm_delete_article, name="confirm-delete"),
    path('delete/<int:pk>/', delete_article, name="delete"),

    # Password Reset
    path('password-reset/', PasswordResetView.as_view(
        template_name='crud_blog/password/password-reset.html',
        subject_template_name='crud_blog/password/password-reset-subject.txt',
        email_template_name='crud_blog/password/password-reset-email.html',
        success_url = reverse_lazy('blog:password_reset_done'),
        form_class=PasswordResetForm,
    ), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='crud_blog/password/password-reset-done.html',
    ), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='crud_blog/password/password-reset-confirm.html',
            form_class=UserPasswordResetConfirmForm,
        ), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='crud_blog/password/password-reset-complete.html'
    ), name='password_reset_complete'),
]

zuri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        # settings.STATIC_URL, document_root=settings.STATIC_ROOT
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

crud_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse("blog:update", kwargs={"pk": self.pk})

    # def get_delete_url(self):
    #     return reverse("blog:confirm-delete")

    def get_confirm_delete_url(self):
        return reverse("blog:delete", kwargs={"pk": self.id})
    



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}: {self.message}"

crud_blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment, Article
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, \
    PasswordResetForm, SetPasswordForm


class ArticleForm(forms.ModelForm):

    image = forms.FileField()

    class Meta:
        model = Article
        fields = [
            "title", "content", "image"
        ]
        widgets = {
            'title': forms.TextInput(attrs={
            'autocomplete': 'title',
            'class': 'form-control oleez-textinput',
            'id': 'validationCustomTitle',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
        }),
        'content': forms.Textarea(attrs={
            "name": "content",
            "id": "content",
            "rows": "10",
            "class": "oleez-textarea form-control",
            "required": "",
        })
    }


class UpdateArticleForm(forms.ModelForm):

    image = forms.FileField()

    class Meta:
        model = Article
        fields = [
            "title", "content", "image"
        ]
        widgets = {
            'title': forms.TextInput(attrs={
            'autocomplete': 'title',
            'class': 'form-control oleez-textinput',
            'id': 'validationCustomTitle',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
        }),
        'content': forms.Textarea(attrs={
            "name": "content",
            "id": "content",
            "rows": "10",
            "class": "oleez-textarea form-control",
            "required": "",
        })
    }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            "message"
        ]
        widgets = {
            'message': forms.Textarea(attrs={
                "name": "message",
                "id": "message",
                "rows": "10",
                "class": "oleez-textarea",
                "required": "",
            })
        }

class UserCreateForm(UserCreationForm):
    """
    A form that inherits from the base *UserCreationForm*,
    and creates a user, with no privileges, from the given 
    username and password.
    """
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword1',
            'required': 'true',
            }
        ),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword2',
            'required': 'true',
            }
        ),
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
        'username': forms.TextInput(attrs={
            'autocomplete': 'username',
            'class': 'form-control',
            'id': 'validationCustomUsername',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
            }
        ),
    }


class UserLoginForm(forms.Form):
    """
    A form that inherits from the base *Form* class,
    and logs a user, with no privileges, from the given 
    username and password.
    """
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'autocomplete': 'username',
            'class': 'form-control user_input',
            'id': 'validationCustomUsername',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control password_input',
            'id': 'confirmPassword1',
            'required': 'true',
            }
        )
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email',
                'id': 'inputEmail3MD',
                'aria-describedby': 'emailHelpId',
                'placeholder': 'Email Address'
            }
        )
    )


class UserPasswordResetConfirmForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(UserPasswordResetConfirmForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm New Password'

crud_blog/views.py
from django.shortcuts import render, redirect
from .forms import UserCreateForm, UserLoginForm, CommentForm, ArticleForm,\
    UpdateArticleForm
from django.contrib.auth import authenticate, login, logout
from .models import Article, Comment
import datetime

date = datetime.datetime.now()

def home(request):
    articles = Article.objects.all().order_by("-timestamp")[:3]

    context = {
        "articles": articles
    }
    return render(request, "crud_blog/index.html", context)


def create_article(request):
    form = ArticleForm()

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get("title")
            image = form.cleaned_data.get("image")
            content = form.cleaned_data.get("content")

            article = Article(
                user=user, title=title, 
                timestamp = date,
                image=image, content=content
            )
            article.save()
            return redirect("blog:home")
        return redirect("blog:create")

    context = {
        "form": form
    }
    return render(request, "crud_blog/create-article.html", context)


def article(request, pk):
    article = Article.objects.get(id=pk)
    comments = Comment.objects.all()
    form = CommentForm()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data.get("message")

            comment = Comment(
                user = request.user,
                message = message,
                article = article
            )
            comment.save()

    context = {
        "article": article,
        "form": form,
        "comments": comments
    }
    return render(request, "crud_blog/blog-single.html", context)


def update_article(request, pk):
    article = Article.objects.get(id=pk)
    form = UpdateArticleForm(instance=article)

    if request.method == "POST":
        form = UpdateArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect("blog:home")
        return redirect("blog:update")

    context = {
        "article": article,
        "form": form
    }
    return render(request, "crud_blog/update-article.html", context)


def confirm_delete_article(request, pk):
    article = Article.objects.get(id=pk)
    return render(request, "crud_blog/confirm-delete-article.html", {"article": article})


def delete_article(request, pk):
    article = Article.objects.get(id=pk)
    article.delete()
    return redirect("blog:home")

def register_page(request):
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("blog:login")
        print("Something's not right.")
        return redirect("blog:register")

    context = {
        "form": form
    }
    return render(request, "crud_blog/register.html", context)


def login_page(request):
    form = UserLoginForm()

    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            print(form)
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(
                request, username=username, password=password
            )
            if user is not None:
                login(request, user)
                return redirect("blog:home")
        return redirect("blog:login")

    context = {
        "form": form
    }
    return render(request, "crud_blog/login.html", context)


def logout_page(request):
    logout(request)
    return redirect("blog:home")


def about(request):
    return render(request, "crud_blog/about.html")

crud_blog/templates/crud_blog/about.html
{% extends "crud_blog/base.html" %} 
{% load static %} 

{% block title %}
Oleez :: About
{% endblock title %}

{% block content %}
    <main class="about-page">
        <div class="container">
            <h1 class="oleez-page-title wow fadeInUp">About Us</h1>
            <p class="oleez-page-header-content wow fadeInUp">A design and development agency based in London. We create digital products that make people’s lives easier.</p>
            <img src="{% static "images/About/about@2x.jpg" %}" alt="about" class="w-100 wow fadeInUp">
            <section class="oleez-about-features">
                <div class="row">
                    <div class="col-md-4 mb-5 mb-md-0 feature-card wow fadeInUp">
                        <h5 class="feature-card-title">Story</h4>
                        <p class="feature-card-content">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, </p>
                    </div>
                    <div class="col-md-4 mb-5 mb-md-0 feature-card wow fadeInUp">
                        <h5 class="feature-card-title">Mission</h4>
                        <p class="feature-card-content">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, </p>
                    </div>
                    <div class="col-md-4 mb-5 mb-md-0 feature-card wow fadeInUp">
                        <h5 class="feature-card-title">Value</h4>
                        <p class="feature-card-content">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, </p>
                    </div>
                </div>
            </section>
            <section class="oleez-what-we-do">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1">
                        <h2 class="section-title wow fadeInUp">What we do</h2>
                        <h4 class="section-subtitle wow fadeInUp">We design thoughtful digital experiences & beautiful brand aesthetics.</h4>
                        <div class="row">
                            <div class="col-md-4 mb-5 mb-md-0 wow fadeInUp">
                                <h5 class="what-we-do-list-title">Market Research</h5>
                                <ul class="what-we-do-list">
                                    <li>Websites</li>
                                    <li>Mobile Applications</li>
                                    <li>Prototyping</li>
                                    <li>Server Administration</li>
                                    <li>Network Solutions</li>
                                    <li>Databases</li>
                                </ul>
                            </div>
                            <div class="col-md-4 mb-5 mb-md-0 wow fadeInUp">
                                <h5 class="what-we-do-list-title">Design & Creative</h5>
                                <ul class="what-we-do-list">
                                    <li>Web Design</li>
                                    <li>Motion Production</li>
                                    <li>User Experience</li>
                                    <li>Illustration</li>
                                    <li>Content Management</li>
                                </ul>
                            </div>
                            <div class="col-md-4 mb-5 mb-md-0 wow fadeInUp">
                                <h5 class="what-we-do-list-title">WordPress</h5>
                                <ul class="what-we-do-list">
                                    <li>Websites</li>
                                    <li>Mobile Applications</li>
                                    <li>Prototyping</li>
                                    <li>Server Administration</li>
                                    <li>Network Solutions</li>
                                    <li>Databases</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section class="oleez-about-work-with-us wow fadeInUp">
                <div class="row">
                    <div class="col-lg-10 offset-lg-1">
                        <h2 class="section-title">We design thoughtful digital experiences & beautiful brand aesthetics.</h2>
                        <p class="section-subtitle">Would you like us to <a href="#!">work</a>  on your brand identity? We would be happy to <a href="#!">help</a>.</p>
                        <a href="#!" class="btn work-with-us-btn">Work with us</a>
                    </div>
                </div>
            </section>
        </div>
    </main>
{% endblock content %}

crud_blog/templates/crud_blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static "vendors/animate.css/animate.min.css" %}">
    <link rel="stylesheet" href="{% static "vendors/slick-carousel/slick.css" %}">
    <link rel="stylesheet" href="{% static "vendors/slick-carousel/slick-theme.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="shortcut icon" href="{% static "images/Logo_2.svg" %}" type="image/x-icon">
    <script src="https://kit.fontawesome.com/6e47be172b.js" crossorigin="anonymous"></script>
    <script src="{% static "vendors/jquery/jquery.min.js" %}"></script>
    <script src="{% static "js/loader.js" %}"></script>
</head>

<body>
    <div class="oleez-loader"></div>
    <header class="oleez-header">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="{% url "blog:home" %}"
            ><img src="{% static 'images/Logo_2.svg' %}" alt="Oleez"
            /></a>
            <ul class="nav nav-actions d-lg-none ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#!" data-toggle="searchModal">
                    <img src="{% static 'images/search.svg' %}" alt="search" />
                    </a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:register' %}">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> REGISTER
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:create' %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i> CREATE
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:logout' %}">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> LOGOUT
                    </a>
                </li>
                {% endif %}
                <li class="nav-item dropdown d-none d-sm-block">
                    <a
                    class="nav-link dropdown-toggle"
                    href="#!"
                    id="languageDropdown"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >ENG</a
                    >
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">
                    <a class="dropdown-item" href="#!">ARB</a>
                    <a class="dropdown-item" href="#!">FRE</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#!" data-toggle="offCanvasMenu">
                    <img src="{% static 'images/social icon@2x.svg' %}" alt="social-nav-toggle" />
                    </a>
                </li>
            </ul>
            <button
            class="navbar-toggler d-lg-none"
            type="button"
            data-toggle="collapse"
            data-target="#oleezMainNav"
            aria-controls="oleezMainNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
            >
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="oleezMainNav">
            <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:home' %}"
                        >Home <span class="sr-only">(current)</span></a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:about' %}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav d-none d-lg-flex">
                <li class="nav-item">
                    <a class="nav-link nav-link-btn" href="#!" data-toggle="searchModal">
                        <img src="{% static 'images/search.svg' %}" alt="search" />
                    </a>
                </li>

                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:register' %}">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> REGISTER
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:create' %}">
                        <i class="fa fa-pencil" aria-hidden="true"></i> CREATE
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:logout' %}">
                        <i class="fa fa-user-circle" aria-hidden="true"></i> LOGOUT
                    </a>
                </li>
                {% endif %}
                
                <li class="nav-item dropdown">
                    <a
                        class="nav-link dropdown-toggle"
                        href="#!"
                        id="languageDropdown"
                        data-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false"
                        >ENG</a
                    >
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">
                        <a class="dropdown-item" href="#!">ARB</a>
                        <a class="dropdown-item" href="#!">FRE</a>
                    </div>
                </li>
                <li class="nav-item ml-5">
                <a
                    class="nav-link pr-0 nav-link-btn"
                    href="#!"
                    data-toggle="offCanvasMenu"
                >
                    <img
                    src="{% static 'images/social icon@2x.svg' %} "
                    alt="social-nav-toggle"
                    />
                </a>
                </li>
            </ul>
            </div>
        </nav>
    </header>

    {% block content %}
      
    {% endblock content %}

    <!-- Footer-->
    <footer class="oleez-footer wow fadeInUp">
    <div class="container">
        <div class="footer-content">
        <div class="row">
            <div class="col-md-6">
            <img src="{% static 'images/Logo_1.svg' %}" alt="oleez" class="footer-logo" />
            <p class="footer-intro-text">
                Don't be shy, get in touch with us and create the world again!
            </p>
            <nav class="footer-social-links">
                <a href="#!">Fb</a>
                <a href="#!">Tw</a>
                <a href="#!">In</a>
                <a href="#!">Be</a>
            </nav>
            </div>
            <div class="col-md-6">
            <div class="row">
                <div class="col-md-6 footer-widget-text">
                <h6 class="widget-title">PHONE</h6>
                <p class="widget-content">+80 (0)5 12 34 95 89</p>
                </div>
                <div class="col-md-6 footer-widget-text">
                <h6 class="widget-title">ENQUIRUES</h6>
                <p class="widget-content">info@oleez.site</p>
                </div>
                <div class="col-md-6 footer-widget-text">
                <h6 class="widget-title">ADDRESS</h6>
                <p class="widget-content">
                    33 rue Burdeau 69089 <br />
                    Paris France
                </p>
                </div>
                <div class="col-md-6 footer-widget-text">
                <h6 class="widget-title">WORK HOURS</h6>
                <p class="widget-content">
                    Weekdays: 09:00 - 18:00 <br />
                    Weekends: 11:00 - 17:00
                </p>
                </div>
            </div>
            </div>
        </div>
        </div>
        <div class="footer-text">
        <p class="mb-md-0">
            © 2020, Oleez.
        </p>
        <p class="mb-0">All right reserved.</p>
        </div>
    </div>
    </footer>

    <!-- Modals -->
    <!-- Off canvas social menu -->
    <nav id="offCanvasMenu" class="off-canvas-menu">
        <button
            type="button"
            class="close"
            aria-label="Close"
            data-dismiss="offCanvasMenu"
        >
            <span aria-hidden="true">&times;</span>
        </button>
        <ul class="oleez-social-menu">
            <li>
            <a href="#!" class="oleez-social-menu-link">Facebook</a>
            </li>
            <li>
            <a href="#!" class="oleez-social-menu-link">Instagram</a>
            </li>
            <li>
            <a href="#!" class="oleez-social-menu-link">Behance</a>
            </li>
            <li>
            <a href="#!" class="oleez-social-menu-link">Dribbble</a>
            </li>
            <li>
            <a href="#!" class="oleez-social-menu-link">Email</a>
            </li>
        </ul>
    </nav>
    <!-- Full screen search box -->
    <div id="searchModal" class="search-modal">
        <button
            type="button"
            class="close"
            aria-label="Close"
            data-dismiss="searchModal"
        >
            <span aria-hidden="true">&times;</span>
        </button>
        <form action="index.html" method="get" class="oleez-overlay-search-form">
            <label for="search" class="sr-only">Search</label>
            <input
            type="search"
            class="oleez-overlay-search-input"
            id="search"
            name="search"
            placeholder="Search here"
            />
        </form>
    </div>

    <script src="{% static "vendors/popper.js/popper.min.js" %}"></script>
    <script src="{% static "vendors/wowjs/wow.min.js" %}"></script>
    <script src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "vendors/slick-carousel/slick.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/landing.js" %}"></script>
    <script>
        new WOW({mobile: false}).init();
    </script>
</body>
</html>

crud_blog/templates/crud_blog/confirm-delete-article.html
{% extends "crud_blog/base.html" %} 
{% load static %} 
{% block title %}
Oleez :: Home
{% endblock title %}
{% block content %}
<main class="error-page">
    <div class="container">
        <h1 class="error-code wow fadeInUp">Confirm Delete</h1>
        <p class="error-description wow fadeInUp">Are you sure you want to delete this article?</p>

        <div class="d-flex mt-3">
            <a href="{{ article.get_confirm_delete_url }}" class="btn btn-danger mr-3">
                Yup, I do.
            </a>
            <a href="" class="btn btn-primary text-white">
                Nay, take me back.
            </a>
        </div>
    </div>
</main>
{% endblock content %}

crud_blog/templates/crud_blog/login.html
{% extends "crud_blog/base.html" %} 
{% load static %} 

{% block title %}
Oleez :: Login
{% endblock title %}

{% block content %}
<style>
    section.login_section{
        padding: 50px;
    }

    div.register{
        max-width: 50%;
        margin: auto;
    }

    @media screen and (max-width: 785px){
        div.register{
            max-width: 90% !important;
        }
    }

    p.h3{
        font-size: 32px;
        font-weight: 600;
        margin-bottom: 20px;
    }

    p.h5{
        font-size: 16px;
    }

    a.register_link{
        padding-left: 10px;
        color: #f7b500;
        font-size: 16px;
    }
</style>

<section class="login_section">
    <div class="container-fluid">
        <div class="register">
            <p class="h3">
                Login
            </p>

            <form method="POST" class="">
                {% csrf_token %}
                
                <div class="form-group">
                  <label for="username">Username: </label>
                  {{ form.username }}
                </div>
                <div class="form-group">
                  <label for="password">Password:</label>
                  {{ form.password }}
                </div>
                <div class="form-group">
                    <p class="h5 text-muted d-flex mb-3">
                        Don't have an account? 
                        <a href="{% url "blog:register" %}" class="register_link">
                            Register
                        </a>
                    </p>
                    <p class="h5 text-muted d-flex mb-3">
                        Forgotten Password? 
                        <a href="{% url "blog:password_reset" %}" class="register_link">
                            Reset
                        </a>
                    </p>
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}