crud_blog/urls.py
from django.urls import path
from .views import home, article, about, register_page, login_page,\
    logout_page, update_article, delete_article, create_article, confirm_delete_article
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from django.contrib.auth.forms import PasswordResetForm
from django.urls import reverse_lazy
from .forms import UserPasswordResetForm, UserPasswordResetConfirmForm


app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('about/', about, name="about"),
    path('register/', register_page, name="register"),
    path('login/', login_page, name="login"),
    path('logout/', logout_page, name="logout"),

    # Article CRUD
    path('create-article/', create_article, name="create"),
    path('<int:pk>/', article, name="article"),
    path('update/<int:pk>/', update_article, name="update"),
    # path('confirm-delete/<int:pk>/', confirm_delete_article, name="confirm-delete"),
    path('delete/<int:pk>/', delete_article, name="delete"),

    # Password Reset
    path('password-reset/', PasswordResetView.as_view(
        template_name='crud_blog/password/password-reset.html',
        subject_template_name='crud_blog/password/password-reset-subject.txt',
        email_template_name='crud_blog/password/password-reset-email.html',
        success_url = reverse_lazy('blog:password_reset_done'),
        form_class=PasswordResetForm,
    ), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='crud_blog/password/password-reset-done.html',
    ), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='crud_blog/password/password-reset-confirm.html',
            form_class=UserPasswordResetConfirmForm,
        ), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='crud_blog/password/password-reset-complete.html'
    ), name='password_reset_complete'),
]

zuri/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        # settings.STATIC_URL, document_root=settings.STATIC_ROOT
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

crud_blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField()
    image = models.ImageField(upload_to="images/", blank=True, null=True)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article", kwargs={"pk": self.pk})

    def get_update_url(self):
        return reverse("blog:update", kwargs={"pk": self.pk})

    # def get_delete_url(self):
    #     return reverse("blog:confirm-delete")

    def get_confirm_delete_url(self):
        return reverse("blog:delete", kwargs={"pk": self.id})
    



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}: {self.message}"

crud_blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment, Article
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, \
    PasswordResetForm, SetPasswordForm


class ArticleForm(forms.ModelForm):

    image = forms.FileField()

    class Meta:
        model = Article
        fields = [
            "title", "content", "image"
        ]
        widgets = {
            'title': forms.TextInput(attrs={
            'autocomplete': 'title',
            'class': 'form-control oleez-textinput',
            'id': 'validationCustomTitle',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
        }),
        'content': forms.Textarea(attrs={
            "name": "content",
            "id": "content",
            "rows": "10",
            "class": "oleez-textarea form-control",
            "required": "",
        })
    }


class UpdateArticleForm(forms.ModelForm):

    image = forms.FileField()

    class Meta:
        model = Article
        fields = [
            "title", "content", "image"
        ]
        widgets = {
            'title': forms.TextInput(attrs={
            'autocomplete': 'title',
            'class': 'form-control oleez-textinput',
            'id': 'validationCustomTitle',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
        }),
        'content': forms.Textarea(attrs={
            "name": "content",
            "id": "content",
            "rows": "10",
            "class": "oleez-textarea form-control",
            "required": "",
        })
    }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            "message"
        ]
        widgets = {
            'message': forms.Textarea(attrs={
                "name": "message",
                "id": "message",
                "rows": "10",
                "class": "oleez-textarea",
                "required": "",
            })
        }

class UserCreateForm(UserCreationForm):
    """
    A form that inherits from the base *UserCreationForm*,
    and creates a user, with no privileges, from the given 
    username and password.
    """
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword1',
            'required': 'true',
            }
        ),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control',
            'id': 'confirmPassword2',
            'required': 'true',
            }
        ),
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
        'username': forms.TextInput(attrs={
            'autocomplete': 'username',
            'class': 'form-control',
            'id': 'validationCustomUsername',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
            }
        ),
    }


class UserLoginForm(forms.Form):
    """
    A form that inherits from the base *Form* class,
    and logs a user, with no privileges, from the given 
    username and password.
    """
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'autocomplete': 'username',
            'class': 'form-control user_input',
            'id': 'validationCustomUsername',
            'aria-describedby': 'inputGroupPrepend',
            'required': 'true',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control password_input',
            'id': 'confirmPassword1',
            'required': 'true',
            }
        )
    )


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email',
                'id': 'inputEmail3MD',
                'aria-describedby': 'emailHelpId',
                'placeholder': 'Email Address'
            }
        )
    )


class UserPasswordResetConfirmForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super(UserPasswordResetConfirmForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'New Password'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm New Password'

crud_blog/views.py
from django.shortcuts import render, redirect
from .forms import UserCreateForm, UserLoginForm, CommentForm, ArticleForm,\
    UpdateArticleForm
from django.contrib.auth import authenticate, login, logout
from .models import Article, Comment
import datetime

date = datetime.datetime.now()

def home(request):
    articles = Article.objects.all().order_by("-timestamp")[:3]

    context = {
        "articles": articles
    }
    return render(request, "crud_blog/index.html", context)


def create_article(request):
    form = ArticleForm()

    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get("title")
            image = form.cleaned_data.get("image")
            content = form.cleaned_data.get("content")

            article = Article(
                user=user, title=title, 
                timestamp = date,
                image=image, content=content
            )
            article.save()
            return redirect("blog:home")
        return redirect("blog:create")

    context = {
        "form": form
    }
    return render(request, "crud_blog/create-article.html", context)


def article(request, pk):
    article = Article.objects.get(id=pk)
    comments = Comment.objects.all()
    form = CommentForm()

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data.get("message")

            comment = Comment(
                user = request.user,
                message = message,
                article = article
            )
            comment.save()

    context = {
        "article": article,
        "form": form,
        "comments": comments
    }
    return render(request, "crud_blog/blog-single.html", context)


def update_article(request, pk):
    article = Article.objects.get(id=pk)
    form = UpdateArticleForm(instance=article)

    if request.method == "POST":
        form = UpdateArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect("blog:home")
        return redirect("blog:update")

    context = {
        "article": article,
        "form": form
    }
    return render(request, "crud_blog/update-article.html", context)


def confirm_delete_article(request, pk):
    article = Article.objects.get(id=pk)
    return render(request, "crud_blog/confirm-delete-article.html", {"article": article})


def delete_article(request, pk):
    article = Article.objects.get(id=pk)
    article.delete()
    return redirect("blog:home")

def register_page(request):
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("blog:login")
        print("Something's not right.")
        return redirect("blog:register")

    context = {
        "form": form
    }
    return render(request, "crud_blog/register.html", context)


def login_page(request):
    form = UserLoginForm()

    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            print(form)
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(
                request, username=username, password=password
            )
            if user is not None:
                login(request, user)
                return redirect("blog:home")
        return redirect("blog:login")

    context = {
        "form": form
    }
    return render(request, "crud_blog/login.html", context)


def logout_page(request):
    logout(request)
    return redirect("blog:home")


def about(request):
    return render(request, "crud_blog/about.html")

crud_blog/templates/crud_blog/password/password-reset-complete.html
{% extends 'base.html' %} 

{% load static %} 

{% block title %} Password Reset Complete - Digital Stade {% endblock title %} 

{% block content %}
<section id="change-password" style="margin-top: 100px;">
  <div class="container">
    <div class="row mt-3 justify-content-center text-center">
      <div class="col-md-10 col-lg-8">
        <div class="mx-auto max-width">
          <h1 class="title font-weight-bold">Password Reset Complete</h1>
          <h3 class="text-muted mt-0 mb-4">
            Yayyy! You have successful reset your password! 😊🌟
          </h3>
          <a
            href="{% url 'accounts:login' %}"
            class="btn btn-danger-form mb-3 btn-block btn-lg"
            >Login Here</a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

crud_blog/templates/crud_blog/password/password-reset-confirm.html
{% extends 'base.html' %} 

{% load static %} 

{% block title %} Password Reset Confrim - Digital Stade {% endblock title %} 

{% block content %}
<section id="forgotten-password" style="margin-top: 100px;">
  <div class="container">
    <div class="row mt-3 justify-content-center text-center">
      <div class="col-md-10 col-lg-8">
        <div class="mx-auto max-width">
          <h1 class="title font-weight-bold">Password Reset Confirm</h1>
          <h3 class="text-muted mt-0 mb-5">Enter your new password:</h3>
          <div class="mx-auto">
            <div class="card border shadow-1-strong mb-5">
              <div class="container">
                <form
                  method="POST"
                  id="forgotten-password-confirm"
                  class="p-3 my-1 mx-0"
                >
                  {% csrf_token %}

                  <div class="form-group">
                    <div class="md-form mt-4">{{ form.new_password1 }}</div>
                  </div>

                  <div class="form-group">
                    <div class="md-form mt-2">{{ form.new_password2 }}</div>
                  </div>

                  <div class="form-group pt-3">
                    <button
                      type="submit"
                      class="btn btn-danger-form mb-3 btn-block btn-lg"
                    >
                      Change Password
                      <i
                        class="fa fa-angle-double-right ft-20"
                        aria-hidden="true"
                      ></i>
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

crud_blog/templates/crud_blog/password/password-reset-done.html
{% extends 'crud_blog/base.html' %} 

{% load static %}  

{% block content %}
<section id="forgotten-password" style="margin-top: 80px; margin-bottom: 80px;">
  <div class="container">
    <div class="row mt-3 justify-content-center text-center">
      <div class="col-md-10 col-lg-8">
        <div class="mx-auto max-width">
          <h1 class="title font-weight-bold mb-4">Password Reset Done</h1>
          <h3 class="text-muted mt-0 mb-3 mt-2">
            “An email with further instructions was sent to the submitted email
            address.”
          </h3>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

crud_blog/templates/crud_blog/password/password-reset-email.html
{% autoescape off %} 

Hi, {{ user.get_username }} 

We've received a
request to reset your password. If you did not make the request, just ignore
this email. Otherwise, you can reset your password using this link. This
password reset valids for the next 15 minutes. 

{{ protocol}}://{{ domain }}{% url 'blog:password_reset_confirm' uidb64=uid token=token %}

Thanks.. The {{ site_name }} Team

P.S. We also love
hearing from you and helping you with any issues you have. Please reply to this
email if you want to ask a question. If you're having trouble clicking the
password reset button, copy and paste the URL below into your web browser. 
{% endautoescape %}

crud_blog/templates/crud_blog/password/password-reset.html
{% extends "crud_blog/base.html" %} 
{% load static %} 

{% block title %}
Oleez :: Reset Password
{% endblock title %}

{% block content %}
<style>
    section.register_section{
        padding: 50px;
    }

    div.register{
        max-width: 50%;
        margin: auto;
    }

    @media screen and (max-width: 785px){
        div.register{
            max-width: 90% !important;
        }
    }
    p.h3{
        font-size: 32px;
        font-weight: 600;
        margin-bottom: 20px;
    }

    input#id_email{
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }
</style>

<section class="register_section">
    <div class="container-fluid">
        <div class="register">
            <p class="h3">
                Reset Password
            </p>

            <form method="POST" class="">
                {% csrf_token %}

                <div class="form-group">
                  <!-- <label for="email">Email:</label> -->
                  {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}